### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np

In [20]:
vector= np.random.rand(10)
print(vector), vector.shape

[0.16780505 0.43302388 0.9050651  0.2618324  0.34802833 0.4422047
 0.14736377 0.51474443 0.26011443 0.01991276]


(None, (10,))

In [22]:
vector_1 = np.random.uniform(0, 1, size=(10))
print(vector_1), vector_1.shape

[0.94947285 0.55937261 0.88913868 0.93169294 0.32384572 0.10842397
 0.64214519 0.33383949 0.11529938 0.93288215]


(None, (10,))

In [12]:
matrix = np.array([[11, 14, 17], [20, 23,26], [29, 32, 35]])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [30]:
vector_sum = np.round(vector + 10,2)
print(vector_sum)

[10.17 10.43 10.91 10.26 10.35 10.44 10.15 10.51 10.26 10.02]


In [27]:
vector_ = vector * 2
print(vector_)

[0.33561009 0.86604776 1.8101302  0.5236648  0.69605665 0.88440939
 0.29472753 1.02948887 0.52022886 0.03982552]


In [28]:
vector_sq= vector ** 2
print(vector_sq)

[2.81585337e-02 1.87509680e-01 8.19142835e-01 6.85562062e-02
 1.21123715e-01 1.95544993e-01 2.17160796e-02 2.64961833e-01
 6.76595178e-02 3.96518038e-04]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [31]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [40]:
result_matrix= np.dot(B,A)
result_matrix,result_matrix.shape

(array([[0.7281, 0.5202],
        [0.2034, 0.2846]]),
 (2, 2))

In [42]:
result_matrix_C = np.dot(result_matrix,C)
result_matrix_C

array([[0.5202],
       [0.2846]])

In [43]:
result_matrix_D = np.dot(result_matrix,D)
result_matrix_D

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [44]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [50]:
vector.T, vector.T.shape, vector.shape

(array([0.16780505, 0.43302388, 0.9050651 , 0.2618324 , 0.34802833,
        0.4422047 , 0.14736377, 0.51474443, 0.26011443, 0.01991276]),
 (10,),
 (10,))

При транспонуванні вектора різниці немає

In [47]:
column_vector = np.expand_dims(vector, axis=1)
column_vector, column_vector.shape

(array([[0.16780505],
        [0.43302388],
        [0.9050651 ],
        [0.2618324 ],
        [0.34802833],
        [0.4422047 ],
        [0.14736377],
        [0.51474443],
        [0.26011443],
        [0.01991276]]),
 (10, 1))

column_vector став двовимірним у порівнянні з vector.T

In [49]:
column_vector.T, column_vector.T.shape

(array([[0.16780505, 0.43302388, 0.9050651 , 0.2618324 , 0.34802833,
         0.4422047 , 0.14736377, 0.51474443, 0.26011443, 0.01991276]]),
 (1, 10))