**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [2]:
import numpy as np

In [13]:
arr = np.array([5, 15, 25, 35, 45])
print(arr)
arr0 = np.zeros((7, ))
print(arr0)
arr1 = np.ones((6,))
print(arr1)
arange = np.arange(10,20,)
print(arange)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]


In [5]:
arr

array([ 5, 15, 25, 35, 45])


---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [19]:
arr = np.array([12, 24, 36, 48, 60])
print(arr * 2)
print(arr + 10)
print(arr ** 2)
print(np.sqrt(arr))

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [24]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(np.mean(data))
print(np.min(data))
print(np.max(data))
print(np.sum(data))

45.42857142857143
18
79
318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [36]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr[0])
print(arr[-1])
print(arr[1:3])
mask = arr > 40
arr[mask]

15
67
[22 35]


array([44, 58, 67])


---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [38]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [64]:
print(matrix.shape)
print(matrix[0,:])
print(matrix[:,1])
print(np.sum(matrix))
print(np.mean(matrix))

(3, 3)
[2 4 6]
[ 4 10 16]
90
10.0
